# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/development/cicd/templates/
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

stages:          # List of stages for jobs, and their order of execution
  - run


run script:       # This job runs in the build stage, which runs first.
  image: wythel/hotel
  stage: run
  before_script:
    - python3 -m venv run
    - source run/bin/activate
    - pip install poetry
    - poetry install
  script:
    - python hotel.py --name $NAME --start-date $START_DATE --end-date $END_DATE
  artifacts:
    paths:
      - "*.png"
      - "*.xlsx"
  parallel:
    matrix:
      # 第一種方法
      # - NAME: 捷絲旅宜蘭礁溪館
      #   START_DATE: 3月23日
      #   END_DATE: 3月31日
      # - NAME: 北投晶泉丰旅
      #   START_DATE: 3月23日
      #   END_DATE: 3月31日
      # - NAME: 礁溪晶泉丰旅
      #   START_DATE: 3月23日
      #   END_DATE: 3月31日
      - NAME: [捷絲旅宜蘭礁溪館, 北投晶泉丰旅, 礁溪晶泉丰旅, 捷絲旅 大阪心齋橋, 捷絲旅臺大尊賢館, Just Sleep Taipei Ximending, just sleep sanchong]
        START_DATE: 3月24日
        END_DATE: 3月31日