name: Hotel Pipeline

on:
  workflow_dispatch:  # 可手動觸發
  push:
    branches:
      - main
      - leo

jobs:
  run-hotel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [捷絲旅宜蘭礁溪館]
        start_date: ["4月2日"]
        end_date: ["4月3日"]
    container:
      image: wythel/hotel
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Set up Python virtual environment
        shell: bash
        run: |
          python3 -m venv run
          source run/bin/activate
          pip install poetry
          poetry install

      - name: Run hotel script
        env:
          NAME: ${{ matrix.name }}
          START_DATE: ${{ matrix.start_date }}
          END_DATE: ${{ matrix.end_date }}
        shell: bash
        run: |
          source run/bin/activate
          python hotel.py --name "$NAME" --start-date "$START_DATE" --end-date "$END_DATE"

      - name: Sanitize name
        id: sanitize
        run: |
          # 把中文轉換為 slug 格式：just_sleep_yilan_jiaoxi 等
          SAFE_NAME=$(echo "${{ matrix.name }}" | base64 | tr -cd '[:alnum:]')
          echo "safe_name=$SAFE_NAME" >> $GITHUB_OUTPUT
        shell: bash

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: hotel-prices-${{ steps.sanitize.outputs.safe_name }}
          path: |
            *.png
            *.xlsx
